### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by nayemmajhar** [aristidesstaffieri/reactDnD-table-demo#1]
Warning: Stateless function components cannot be given refs (See ref "child" in Table created by DragDropContext(Table)). Attempts to access this ref will fail.

**Comment by aristidesstaffieri** [comment]
This is under discussion [here](https://github.com/reactjs/react-redux/issues/141), I'm not sure if there's a resolution yet. I cleaned out `node_modules`, updated all dependencies and the demo is working.

**Comment by nayemmajhar** [comment]
no. It's not working. still same issue.

update: my bad. It's working. I am learning React-dnd but there is no simple tutorial or somethings. 
BTW, Thanks

**Comment by aristidesstaffieri** [comment]
No problem, let me know if I can help in any other ways. Closing this.
